{
 "title": "kafka-broker-ingress Kafka metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "kafka_producer_node_outgoing_byte_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_node_outgoing_byte_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_response_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_response_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_metadata_age",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_metadata_age{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_produce_throttle_time_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_produce_throttle_time_max{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_request_size_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_request_size_max{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_node_request_size_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_node_request_size_max{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_record_queue_time_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_record_queue_time_max{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_io_time_ns_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_io_time_ns_avg{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_record_queue_time_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_record_queue_time_avg{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_request_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_request_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_outgoing_byte_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_outgoing_byte_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_node_request_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_node_request_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_record_error_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_record_error_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_connection_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_connection_count{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_waiting_threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_waiting_threads{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_request_latency_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_request_latency_max{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_successful_reauthentication_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_successful_reauthentication_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_connection_creation_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_connection_creation_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_node_response_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_node_response_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_incoming_byte_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_incoming_byte_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_successful_authentication_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_successful_authentication_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_successful_authentication_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_successful_authentication_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_batch_split_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_batch_split_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_node_incoming_byte_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_node_incoming_byte_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_record_size_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_record_size_max{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_record_send_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_record_send_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_node_incoming_byte_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_node_incoming_byte_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_txn_begin_time_ns_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_txn_begin_time_ns_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_failed_reauthentication_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_failed_reauthentication_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_buffer_exhausted_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_buffer_exhausted_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_record_retry_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_record_retry_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_txn_commit_time_ns_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_txn_commit_time_ns_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_produce_throttle_time_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_produce_throttle_time_avg{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_io_wait_time_ns_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_io_wait_time_ns_avg{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_records_per_request_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_records_per_request_avg{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_batch_split_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_batch_split_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_bufferpool_wait_time_ns_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_bufferpool_wait_time_ns_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_node_request_latency_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_node_request_latency_max{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_failed_authentication_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_failed_authentication_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_topic_record_retry_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_topic_record_retry_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_io_wait_time_ns_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_io_wait_time_ns_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_node_response_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_node_response_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_topic_byte_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_topic_byte_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_node_outgoing_byte_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_node_outgoing_byte_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_io_ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_io_ratio{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_request_latency_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_request_latency_avg{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_topic_record_send_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_topic_record_send_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_network_io_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_network_io_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_compression_rate_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_compression_rate_avg{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_app_info_start_time_ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_app_info_start_time_ms{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_batch_size_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_batch_size_max{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_successful_reauthentication_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_successful_reauthentication_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_request_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_request_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_node_request_latency_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_node_request_latency_avg{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_request_size_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_request_size_avg{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_topic_record_error_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_topic_record_error_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_network_io_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_network_io_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_topic_record_error_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_topic_record_error_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_successful_authentication_no_reauth_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_successful_authentication_no_reauth_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_record_error_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_record_error_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_failed_reauthentication_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_failed_reauthentication_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_batch_size_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_batch_size_avg{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_select_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_select_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "event_dispatch_latencies_ms_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "event_dispatch_latencies_ms_count{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_record_size_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_record_size_avg{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_failed_authentication_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_failed_authentication_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_io_time_ns_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_io_time_ns_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_buffer_total_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_buffer_total_bytes{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_node_request_size_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_node_request_size_avg{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_bufferpool_wait_ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_bufferpool_wait_ratio{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_topic_byte_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_topic_byte_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_txn_send_offsets_time_ns_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_txn_send_offsets_time_ns_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_response_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_response_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_select_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_select_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_io_wait_ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_io_wait_ratio{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_iotime_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_iotime_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_reauthentication_latency_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_reauthentication_latency_avg{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_io_wait_time_ns_totalkafka_producer_io_wait_time_ns_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_io_wait_time_ns_totalkafka_producer_io_wait_time_ns_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_buffer_available_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_buffer_available_bytes{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_connection_close_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_connection_close_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "event_dispatch_latencies_ms_bucket",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "event_dispatch_latencies_ms_bucket{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_topic_record_retry_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_topic_record_retry_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_buffer_exhausted_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_buffer_exhausted_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_record_retry_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_record_retry_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_reauthentication_latency_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_reauthentication_latency_max{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_bufferpool_wait_time_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_bufferpool_wait_time_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_txn_abort_time_ns_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_txn_abort_time_ns_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_connection_close_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_connection_close_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_incoming_byte_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_incoming_byte_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_txn_init_time_ns_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_txn_init_time_ns_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_topic_record_send_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_topic_record_send_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_requests_in_flight",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_requests_in_flight{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_record_send_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_record_send_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "event_dispatch_latencies_ms_sum",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "event_dispatch_latencies_ms_sum{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_flush_time_ns_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_flush_time_ns_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_connection_creation_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_connection_creation_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_node_request_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_node_request_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "event_dispatch_latencies_ms_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "event_dispatch_latencies_ms_max{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_topic_compression_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_topic_compression_rate{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_io_waittime_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_io_waittime_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_producer_outgoing_byte_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_producer_outgoing_byte_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "event_count_1_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "event_count_1_total{job=\"kafka-broker-ingress\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}