{
 "title": "source-metrics-service Kafka metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "kafka_consumer_node_request_latency_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_node_request_latency_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_io_wait_time_ns_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_io_wait_time_ns_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_fetch_manager_bytes_consumed_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_bytes_consumed_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_sync_time_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_sync_time_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_join_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_join_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_partition_revoked_latency_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_partition_revoked_latency_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_connection_creation_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_connection_creation_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_heartbeat_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_heartbeat_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_iotime_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_iotime_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_response_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_response_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_join_time_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_join_time_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_connection_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_connection_count{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_request_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_request_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_node_incoming_byte_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_node_incoming_byte_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "event_dispatch_latencies_ms_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "event_dispatch_latencies_ms_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_sync_time_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_sync_time_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_reauthentication_latency_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_reauthentication_latency_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_partition_revoked_latency_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_partition_revoked_latency_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_successful_reauthentication_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_successful_reauthentication_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_io_wait_ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_io_wait_ratio{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_poll_idle_ratio_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_poll_idle_ratio_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_reauthentication_latency_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_reauthentication_latency_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_last_rebalance_seconds_ago",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_last_rebalance_seconds_ago{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_rebalance_rate_per_hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_rebalance_rate_per_hour{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_successful_authentication_no_reauth_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_successful_authentication_no_reauth_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_failed_authentication_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_failed_authentication_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_node_request_size_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_node_request_size_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_fetch_manager_fetch_latency_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_outgoing_byte_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_outgoing_byte_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_fetch_manager_fetch_throttle_time_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_throttle_time_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "event_dispatch_latencies_ms_bucket",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "event_dispatch_latencies_ms_bucket{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_last_poll_seconds_ago",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_last_poll_seconds_ago{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_heartbeat_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_heartbeat_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_node_request_size_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_node_request_size_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "event_processing_latencies_ms_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "event_processing_latencies_ms_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_last_heartbeat_seconds_ago",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_last_heartbeat_seconds_ago{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "event_dispatch_latencies_ms_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "event_dispatch_latencies_ms_count{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_join_time_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_join_time_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_node_request_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_node_request_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "event_processing_latencies_ms_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "event_processing_latencies_ms_count{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_successful_authentication_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_successful_authentication_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_node_outgoing_byte_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_node_outgoing_byte_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_join_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_join_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_select_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_select_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_fetch_manager_fetch_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_assigned_partitions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_assigned_partitions{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_failed_reauthentication_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_failed_reauthentication_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_node_outgoing_byte_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_node_outgoing_byte_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_response_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_response_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_fetch_manager_records_per_request_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_per_request_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_connection_close_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_connection_close_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_failed_rebalance_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_failed_rebalance_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_node_response_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_node_response_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_failed_authentication_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_failed_authentication_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_fetch_manager_records_lead_min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lead_min{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_node_request_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_node_request_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_commit_sync_time_ns_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_commit_sync_time_ns_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_rebalance_latency_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_rebalance_latency_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_commit_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_commit_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_rebalance_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_rebalance_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_fetch_manager_bytes_consumed_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_bytes_consumed_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_connection_creation_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_connection_creation_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_fetch_manager_fetch_latency_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_rebalance_latency_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_rebalance_latency_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_partition_lost_latency_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_partition_lost_latency_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_fetch_manager_records_lag_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_io_wait_time_ns_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_io_wait_time_ns_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_successful_authentication_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_successful_authentication_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "event_processing_latencies_ms_bucket",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "event_processing_latencies_ms_bucket{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_request_size_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_request_size_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_io_time_ns_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_io_time_ns_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_successful_reauthentication_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_successful_reauthentication_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_fetch_manager_fetch_throttle_time_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_throttle_time_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_outgoing_byte_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_outgoing_byte_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_io_waittime_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_io_waittime_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_io_time_ns_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_io_time_ns_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "event_dispatch_in_flight_count_1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "event_dispatch_in_flight_count_1{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_time_between_poll_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_time_between_poll_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_fetch_manager_records_consumed_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_failed_reauthentication_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_failed_reauthentication_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_request_size_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_request_size_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_partition_lost_latency_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_partition_lost_latency_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_select_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_select_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_commit_latency_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_commit_latency_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_io_ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_io_ratio{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "event_processing_latencies_ms_sum",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "event_processing_latencies_ms_sum{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_fetch_manager_records_consumed_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_fetch_manager_fetch_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_incoming_byte_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_incoming_byte_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_node_response_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_node_response_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_app_info_start_time_ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_app_info_start_time_ms{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_incoming_byte_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_incoming_byte_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_commit_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_commit_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_network_io_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_network_io_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_fetch_manager_preferred_read_replica",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_preferred_read_replica{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_fetch_manager_fetch_size_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_size_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_heartbeat_response_time_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_heartbeat_response_time_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_request_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_request_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_sync_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_sync_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_failed_rebalance_rate_per_hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_failed_rebalance_rate_per_hour{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_sync_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_sync_rate{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_fetch_manager_fetch_size_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_size_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_network_io_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_network_io_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_time_between_poll_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_time_between_poll_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_partition_assigned_latency_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_partition_assigned_latency_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_connection_close_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_connection_close_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "event_count_1_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "event_count_1_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_rebalance_latency_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_rebalance_latency_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_node_incoming_byte_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_node_incoming_byte_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "event_dispatch_latencies_ms_sum",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "event_dispatch_latencies_ms_sum{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_commit_latency_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_commit_latency_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_committed_time_ns_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_committed_time_ns_total{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_node_request_latency_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_node_request_latency_avg{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumer_coordinator_partition_assigned_latency_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_partition_assigned_latency_max{job=\"source-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}